version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/indian_calculation
      - gem-data:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  gem-data:
    driver: local
